import { useState } from 'react';
import {
  ArrowRight, CheckCircle2, Circle, CircleDot, Loader2, RefreshCcw, ShieldAlert, TriangleAlert,
} from 'lucide-react';
import type { RplAssessment } from '../../rpl/types';
import { RPL_DISCLAIMER } from '../../rpl/types';

/** Confidence badge: neutral, never presented as certification. */
export function ConfBadge({ c }: { c: string }) {
  const tone =
    c === 'High confidence'
      ? 'border-good-line bg-good-soft text-good'
      : c === 'Medium confidence'
        ? 'border-amber-200 bg-amber-50 text-amber-700'
        : 'border-bad-soft bg-bad-soft text-bad';
  return <span className={`pill text-[11px] ${tone}`}>{c}</span>;
}

export function MappingStatusChip({ s }: { s: string }) {
  const tone =
    s === 'Demonstrated'
      ? 'border-good-line bg-good-soft text-good'
      : s === 'Partially Demonstrated'
        ? 'border-amber-200 bg-amber-50 text-amber-700'
        : s === 'Evidence Required'
          ? 'border-bad-soft bg-bad-soft text-bad'
          : 'text-ink-faint';
  return <span className={`pill text-[11px] ${tone}`}>{s}</span>;
}

/** The mandated AI-assessment disclaimer bar (reused across screens). */
export function AiDisclaimer({ text = RPL_DISCLAIMER }: { text?: string }) {
  return (
    <div className="rounded-xl border border-brand-100 bg-brand-50/60 p-3 text-xs leading-relaxed text-ink-soft">
      <strong className="text-ink">AI Assessment Indicator.</strong> {text}
    </div>
  );
}

export function DemoRibbon({ show }: { show: boolean }) {
  if (!show) return null;
  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-3 text-xs font-bold tracking-wide text-amber-700">
      DEMO DATA — NOT REAL CANDIDATE INFORMATION
    </div>
  );
}

function Bar({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="flex items-baseline justify-between text-sm">
        <span className="font-medium text-ink">{label}</span>
        <span className="font-display font-bold text-ink">{value}%</span>
      </div>
      <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100" role="presentation">
        <div className="h-full rounded-full bg-gradient-to-r from-brand-600 to-accent-500" style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}

interface Props {
  assessment: RplAssessment;
  analyzing: boolean;
  source: 'ai' | 'demo' | null;
  onContinue: () => void;
  onRegenerate: () => void;
}

export default function SkillAnalysis({ assessment, analyzing, source, onContinue, onRegenerate }: Props) {
  const [tab, setTab] = useState<'skills' | 'mapping'>('skills');

  if (analyzing) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-20 text-center sm:px-6">
        <Loader2 className="mx-auto h-12 w-12 animate-spin text-brand-600" aria-hidden="true" />
        <h1 className="mt-6 font-display text-2xl font-extrabold text-ink">AI Skill Analysis running…</h1>
        <p className="mt-2 text-ink-soft">Extracting skills from your experience and comparing them with the {assessment.roleName} competency framework.</p>
      </div>
    );
  }

  const skills = assessment.skills;
  const mappings = assessment.mappings;
  const demonstrated = mappings.filter((m) => m.status === 'Demonstrated').length;
  const partial = mappings.filter((m) => m.status === 'Partially Demonstrated').length;

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6">
      <DemoRibbon show={!!assessment.demo} />

      {/* AI Skill Analysis */}
      <section className="card mt-4 p-6 sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="font-display text-2xl font-extrabold text-ink">AI Skill Analysis</h1>
            <p className="mt-1 text-sm text-ink-soft">
              What the AI found in your experience for <strong className="text-ink">{assessment.roleName}</strong>.
              {' '}{source === 'ai' ? 'Generated live by AI.' : 'Generated by the built-in assessment engine (AI unavailable).'}
            </p>
          </div>
          <button onClick={onRegenerate} className="btn btn-ghost btn-md shrink-0" title="Run the analysis again">
            <RefreshCcw className="h-4 w-4" aria-hidden="true" />
            Re-run
          </button>
        </div>

        <div className="mt-5 rounded-xl border border-line p-1.5 flex gap-1">
          <button onClick={() => setTab('skills')} className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${tab === 'skills' ? 'bg-brand-50 text-brand-700' : 'text-ink-soft hover:text-ink'}`}>
            Skills extracted ({skills.length})
          </button>
          <button onClick={() => setTab('mapping')} className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${tab === 'mapping' ? 'bg-brand-50 text-brand-700' : 'text-ink-soft hover:text-ink'}`}>
            Competency mapping ({demonstrated + partial}/{mappings.length})
          </button>
        </div>

        {tab === 'skills' && (
          <ul className="mt-4 space-y-2.5">
            {skills.map((s) => (
              <li key={s.name} className="rounded-xl border border-line bg-paper p-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="font-semibold text-ink">{s.name}</span>
                  <span className="flex items-center gap-1.5">
                    <span className="pill text-[11px] text-ink-faint">{s.category}</span>
                    <ConfBadge c={s.confidence} />
                  </span>
                </div>
                <div className="mt-1 flex items-start gap-1.5 text-xs text-ink-faint">
                  {s.confidence === 'High confidence' ? <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-good" aria-hidden="true" /> : s.confidence === 'Medium confidence' ? <CircleDot className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" aria-hidden="true" /> : <Circle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-bad" aria-hidden="true" />}
                  <span>Evidence source: {s.source}</span>
                </div>
              </li>
            ))}
            {skills.length === 0 && <li className="text-sm text-ink-soft">No skills were detected — try describing your work in more detail and re-running the analysis.</li>}
          </ul>
        )}

        {tab === 'mapping' && (
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-left text-sm" aria-label="Competency mapping">
              <thead>
                <tr className="border-b border-line text-xs uppercase tracking-wide text-ink-faint">
                  <th className="py-2 pr-3 font-semibold">Competency</th>
                  <th className="py-2 pr-3 font-semibold">Evidence</th>
                  <th className="py-2 font-semibold">Assessment Status</th>
                </tr>
              </thead>
              <tbody>
                {mappings.map((m) => (
                  <tr key={m.competency} className="border-b border-line/60 last:border-0">
                    <td className="py-2.5 pr-3 font-semibold text-ink">{m.competency}</td>
                    <td className="py-2.5 pr-3 text-ink-soft">{m.evidence}</td>
                    <td className="py-2.5"><MappingStatusChip s={m.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="mt-3 text-xs text-ink-faint">
              Status labels are preliminary indicators, not validated competence. An authorized assessor makes the final decision.
            </p>
          </div>
        )}

        <div className="mt-5">
          <AiDisclaimer />
        </div>
      </section>

      {/* Pre-readiness preview (before quiz) */}
      <section className="card mt-4 p-6">
        <h2 className="font-display text-lg font-bold text-ink">Early signal</h2>
        <p className="mt-1 text-xs text-ink-soft">Preliminary — assessment answers and evidence will change these numbers.</p>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          {(() => {
            const full = mappings.filter((m) => m.status === 'Demonstrated').length;
            const cov = Math.round(((full + partial * 0.5) / (mappings.length || 1)) * 100);
            return <Bar label="Competency coverage" value={cov} />;
          })()}
          <Bar label="Evidence items recorded" value={Math.min(100, assessment.evidence.length * 25)} />
        </div>
      </section>

      <div className="mt-6 flex flex-col items-center gap-3 sm:flex-row-reverse">
        <button onClick={onContinue} className="btn btn-primary btn-xl w-full sm:w-auto">
          Start Skill Assessment
          <ArrowRight className="h-5 w-5" aria-hidden="true" />
        </button>
        <div className="flex items-center gap-2 text-xs text-ink-soft sm:mr-auto">
          <ShieldAlert className="h-3.5 w-3.5" aria-hidden="true" />
          Preliminary only — final RPL decisions need an authorized assessor.
        </div>
        {mappings.some((m) => m.status !== 'Demonstrated') && (
          <span className="flex items-center gap-1.5 text-xs text-amber-700 sm:ml-auto sm:mr-auto sm:absolute sm:right-8">
            <TriangleAlert className="h-3.5 w-3.5" aria-hidden="true" />
          </span>
        )}
      </div>
    </div>
  );
}
