import { useState } from 'react';
import {
  ArrowRight, CheckCircle2, Circle, CircleDot, Loader2, Play, RefreshCcw, RotateCcw,
  ShieldAlert, Square, TriangleAlert,
} from 'lucide-react';
import type { RplAssessment } from '../../rpl/types';
import { RPL_DISCLAIMER } from '../../rpl/types';
import {
  assessedCount,
  allCompetenciesAssessed,
  competencyPlan,
  competencyRun,
  currentCompetency,
  QUESTIONS_PER_COMPETENCY,
} from '../../rpl/skills-review';

/** Confidence badge: neutral, never presented as certification. */
export function ConfBadge({ c }: { c: string }) {
  const tone =
    c === 'High confidence'
      ? 'border-good-line bg-good-soft text-good'
      : c === 'Medium confidence'
        ? 'border-amber-200 bg-amber-50 text-amber-700'
        : 'border-bad-soft bg-bad-soft text-bad';
  return <span className={`pill text-[11px] ${tone}`}>{c}</span>;
}

export function MappingStatusChip({ s }: { s: string }) {
  const tone =
    s === 'Demonstrated'
      ? 'border-good-line bg-good-soft text-good'
      : s === 'Partially Demonstrated'
        ? 'border-amber-200 bg-amber-50 text-amber-700'
        : s === 'Evidence Required'
          ? 'border-bad-soft bg-bad-soft text-bad'
          : 'text-ink-faint';
  return <span className={`pill text-[11px] ${tone}`}>{s}</span>;
}

/** The mandated AI-assessment disclaimer bar (reused across screens). */
export function AiDisclaimer({ text = RPL_DISCLAIMER }: { text?: string }) {
  return (
    <div className="rounded-xl border border-brand-100 bg-brand-50/60 p-3 text-xs leading-relaxed text-ink-soft">
      <strong className="text-ink">AI Assessment Indicator.</strong> {text}
    </div>
  );
}

function Bar({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="flex items-baseline justify-between text-sm">
        <span className="font-medium text-ink">{label}</span>
        <span className="font-display font-bold text-ink">{value}%</span>
      </div>
      <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100" role="presentation">
        <div className="h-full rounded-full bg-gradient-to-r from-brand-600 to-accent-500" style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}

/** Per-competency completion chip: Not started / In progress / ✓ Assessed (+ score). */
function CompetencyStatusChip({ state, scorePct }: { state: string; scorePct: number }) {
  if (state === 'assessed') {
    return (
      <span className="pill border-good-line bg-good-soft text-[11px] text-good">
        <CheckCircle2 className="mr-1 inline h-3 w-3" aria-hidden="true" />
        Assessed · {scorePct}%
      </span>
    );
  }
  if (state === 'in-progress') {
    return <span className="pill border-amber-200 bg-amber-50 text-[11px] text-amber-700">In progress</span>;
  }
  return <span className="pill text-[11px] text-ink-faint">Not started</span>;
}

interface Props {
  assessment: RplAssessment;
  analyzing: boolean;
  source: 'ai' | 'local' | null;
  onRegenerate: () => void;
  onStartCompetency: (competency: string) => void;
  onResumeCompetency: (competency: string) => void;
  onRetakeCompetency: (competency: string) => void;
  onResults: () => void;
}

export default function SkillAnalysis({
  assessment, analyzing, source, onRegenerate, onStartCompetency, onResumeCompetency, onRetakeCompetency, onResults,
}: Props) {
  const [tab, setTab] = useState<'skills' | 'mapping'>('skills');

  if (analyzing) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-20 text-center sm:px-6">
        <Loader2 className="mx-auto h-12 w-12 animate-spin text-brand-600" aria-hidden="true" />
        <h1 className="mt-6 font-display text-2xl font-extrabold text-ink">AI Skill Analysis running…</h1>
        <p className="mt-2 text-ink-soft">Extracting skills from your experience and comparing them with the {assessment.roleName} competency framework.</p>
      </div>
    );
  }

  const skills = assessment.skills;
  const mappings = assessment.mappings;
  const demonstrated = mappings.filter((m) => m.status === 'Demonstrated').length;
  const partial = mappings.filter((m) => m.status === 'Partially Demonstrated').length;
  const plan = competencyPlan(assessment);
  const assessed = assessedCount(assessment);
  const allDone = allCompetenciesAssessed(assessment);
  const resume = currentCompetency(assessment);

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6">
      {/* AI Skill Analysis */}
      <section className="card p-6 sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="font-display text-2xl font-extrabold text-ink">AI Skill Analysis</h1>
            <p className="mt-1 text-sm text-ink-soft">
              What the AI found in your experience for <strong className="text-ink">{assessment.roleName}</strong>.
              {' '}{source === 'ai' ? 'Generated live by AI.' : source === 'local' ? 'Generated by the built-in assessment engine (AI unavailable).' : ''}
            </p>
          </div>
          <button onClick={onRegenerate} className="btn btn-ghost btn-md shrink-0" title="Run the analysis again">
            <RefreshCcw className="h-4 w-4" aria-hidden="true" />
            Re-run
          </button>
        </div>

        <div className="mt-5 rounded-xl border border-line p-1.5 flex gap-1">
          <button onClick={() => setTab('skills')} className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${tab === 'skills' ? 'bg-brand-50 text-brand-700' : 'text-ink-soft hover:text-ink'}`}>
            Skills extracted ({skills.length})
          </button>
          <button onClick={() => setTab('mapping')} className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${tab === 'mapping' ? 'bg-brand-50 text-brand-700' : 'text-ink-soft hover:text-ink'}`}>
            Competency mapping ({demonstrated + partial}/{mappings.length})
          </button>
        </div>

        {tab === 'skills' && (
          <ul className="mt-4 space-y-2.5">
            {skills.map((s) => (
                <li key={s.name} className="rounded-xl border border-line bg-paper p-4">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <span className="font-semibold text-ink">{s.name}</span>
                    <span className="flex items-center gap-1.5">
                      <span className="pill text-[11px] text-ink-faint">{s.category}</span>
                      <ConfBadge c={s.confidence} />
                    </span>
                  </div>
                  <div className="mt-1 flex items-start gap-1.5 text-xs text-ink-faint">
                    {s.confidence === 'High confidence' ? <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-good" aria-hidden="true" /> : s.confidence === 'Medium confidence' ? <CircleDot className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" aria-hidden="true" /> : <Circle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-bad" aria-hidden="true" />}
                    <span>Evidence source: {s.source}</span>
                  </div>
                </li>
              ))}
            {skills.length === 0 && <li className="text-sm text-ink-soft">No skills were detected — try describing your work in more detail and re-running the analysis.</li>}
          </ul>
        )}

        {tab === 'mapping' && (
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-left text-sm" aria-label="Competency mapping">
              <thead>
                <tr className="border-b border-line text-xs uppercase tracking-wide text-ink-faint">
                  <th className="py-2 pr-3 font-semibold">Competency</th>
                  <th className="py-2 pr-3 font-semibold">Evidence</th>
                  <th className="py-2 font-semibold">Assessment Status</th>
                </tr>
              </thead>
              <tbody>
                {mappings.map((m) => (
                  <tr key={m.competency} className="border-b border-line/60 last:border-0">
                    <td className="py-2.5 pr-3 font-semibold text-ink">{m.competency}</td>
                    <td className="py-2.5 pr-3 text-ink-soft">{m.evidence}</td>
                    <td className="py-2.5"><MappingStatusChip s={m.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="mt-3 text-xs text-ink-faint">
              Status labels are preliminary indicators, not validated competence. An authorized assessor makes the final decision.
            </p>
          </div>
        )}

        <div className="mt-5">
          <AiDisclaimer />
        </div>
      </section>

      {/* Per-competency self-paced assessments */}
      {plan.length > 0 && (
        <section className="card mt-4 p-6 sm:p-8">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <h2 className="font-display text-lg font-bold text-ink">Your assessments</h2>
              <p className="mt-1 text-sm text-ink-soft">
                One short assessment ({QUESTIONS_PER_COMPETENCY} questions) per skill. Take them at your own pace — leave and come back any time; your progress is saved on this device.
              </p>
            </div>
          </div>

          {/* Completion reminder — the candidate must finish ALL competencies. */}
          <div className={`mt-4 rounded-xl border p-3.5 text-sm ${allDone ? 'border-good-line bg-good-soft text-good' : 'border-amber-200 bg-amber-50 text-amber-700'}`}>
            <strong>{allDone ? 'All skills assessed.' : 'Complete all skills before your final report.'}</strong>{' '}
            {allDone
              ? 'You can now generate your combined RPL assessment report.'
              : `${assessed} of ${plan.length} skill assessments completed — ${plan.length - assessed} remaining.`}
          </div>
          <div className="mt-3 h-2 w-full overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-valuenow={assessed} aria-valuemin={0} aria-valuemax={plan.length}>
            <div className="h-full rounded-full bg-gradient-to-r from-brand-600 to-accent-500 transition-all" style={{ width: `${(assessed / plan.length) * 100}%` }} />
          </div>

          <ul className="mt-4 space-y-2.5">
            {plan.map((c) => {
              const run = competencyRun(assessment, c);
              const disabled = run.state === 'loading';
              return (
                <li key={c} className="flex flex-col gap-3 rounded-xl border border-line bg-paper p-4 sm:flex-row sm:items-center">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-semibold text-ink">{c}</span>
                      <CompetencyStatusChip state={run.state} scorePct={run.scorePct} />
                    </div>
                    <div className="mt-0.5 text-xs text-ink-faint">
                      {run.state === 'assessed' && `Completed — preliminary score ${run.scorePct}%. You can retake it if you want.`}
                      {run.state === 'in-progress' && `In progress — ${run.answeredCount}/${run.totalQuestions} answered. Continue where you left off.`}
                      {run.state === 'loading' && 'Preparing your questions…'}
                      {run.state === 'not-started' && 'Not started yet — a short 3-question assessment.'}
                    </div>
                  </div>
                  <div className="flex shrink-0 gap-2">
                    {run.state === 'assessed' ? (
                      <button onClick={() => onRetakeCompetency(c)} disabled={disabled} className="btn btn-ghost btn-md">
                        <RotateCcw className="h-4 w-4" aria-hidden="true" />
                        Retake
                      </button>
                    ) : run.state === 'in-progress' ? (
                      <button onClick={() => onResumeCompetency(c)} className="btn btn-primary btn-md">
                        <Play className="h-4 w-4" aria-hidden="true" />
                        Resume
                      </button>
                    ) : (
                      <button onClick={() => onStartCompetency(c)} disabled={disabled} className="btn btn-primary btn-md">
                        {disabled ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <Play className="h-4 w-4" aria-hidden="true" />}
                        Take Assessment
                      </button>
                    )}
                  </div>
                </li>
              );
            })}
          </ul>

          <div className="mt-5 flex flex-col gap-3 sm:flex-row-reverse">
            {resume && !allDone && (
              <button onClick={() => onResumeCompetency(resume)} className="btn btn-primary btn-lg w-full sm:w-auto">
                Continue: {resume}
                <ArrowRight className="h-5 w-5" aria-hidden="true" />
              </button>
            )}
            {!resume && !allDone && (
              <button onClick={() => onStartCompetency(plan.find((c) => competencyRun(assessment, c).state !== 'assessed') ?? plan[0])} className="btn btn-primary btn-lg w-full sm:w-auto">
                Start next assessment
                <ArrowRight className="h-5 w-5" aria-hidden="true" />
              </button>
            )}
            {allDone && (
              <button onClick={onResults} className="btn btn-primary btn-xl w-full sm:w-auto">
                See My Skill Gaps
                <ArrowRight className="h-5 w-5" aria-hidden="true" />
              </button>
            )}
            {!allDone && (
              <div className="flex items-center gap-2 text-xs text-ink-soft sm:mr-auto">
                <Square className="h-3.5 w-3.5" aria-hidden="true" />
                The combined RPL report unlocks after every skill assessment is complete.
              </div>
            )}
          </div>
        </section>
      )}

      {/* Pre-readiness preview (before assessments) */}
      <section className="card mt-4 p-6">
        <h2 className="font-display text-lg font-bold text-ink">Early signal</h2>
        <p className="mt-1 text-xs text-ink-soft">Preliminary — assessment answers and evidence will change these numbers.</p>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          {(() => {
            const full = mappings.filter((m) => m.status === 'Demonstrated').length;
            const cov = Math.round(((full + partial * 0.5) / (mappings.length || 1)) * 100);
            return <Bar label="Competency coverage" value={cov} />;
          })()}
          <Bar label="Evidence items recorded" value={Math.min(100, assessment.evidence.length * 25)} />
        </div>
      </section>

      <div className="mt-6 flex flex-col items-center gap-3 sm:flex-row-reverse">
        {plan.length === 0 && (
          <div className="text-sm text-ink-soft">Run the skill analysis to load your competency list.</div>
        )}
        <div className="flex items-center gap-2 text-xs text-ink-soft sm:mr-auto">
          <ShieldAlert className="h-3.5 w-3.5" aria-hidden="true" />
          Preliminary only — final RPL decisions need an authorized assessor.
        </div>
        {mappings.some((m) => m.status !== 'Demonstrated') && (
          <span className="flex items-center gap-1.5 text-xs text-amber-700 sm:ml-auto sm:mr-auto sm:absolute sm:right-8">
            <TriangleAlert className="h-3.5 w-3.5" aria-hidden="true" />
          </span>
        )}
      </div>
    </div>
  );
}
